### ISSUE TITLE
0.8 regression: IndexOutOfBoundsException when collecting dependencies

### ISSUE THREAD

**Issue by ZacSweers** [square/gradle-dependencies-sorter#110]
Working on trying to figure out which file it sees this on

```
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at cash.grammar.kotlindsl.utils.DependencyExtractor.findIdentifier(DependencyExtractor.kt:253)
        at cash.grammar.kotlindsl.utils.DependencyExtractor.parseDependencyDeclaration(DependencyExtractor.kt:154)
        at cash.grammar.kotlindsl.utils.DependencyExtractor.collectDependencies(DependencyExtractor.kt:48)
        at com.squareup.sort.kotlin.KotlinSorter.enterNamedBlock(KotlinSorter.kt:84)
        at com.squareup.cash.grammar.KotlinParser$NamedBlockContext.enterRule(KotlinParser.java:1491)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at cash.grammar.kotlindsl.parse.Parser.listener(Parser.kt:96)
        at com.squareup.sort.kotlin.KotlinSorter$Companion.of(KotlinSorter.kt:182)
        at com.squareup.sort.Sorter$Companion.of(Sorter.kt:20)
        at com.squareup.sort.SortCommand$sort$1.invoke(SortCommand.kt:118)
        at com.squareup.sort.SortCommand$sort$1.invoke(SortCommand.kt:116)
        at com.squareup.sort.SortCommand.sort$lambda$0(SortCommand.kt:116)

```

**Comment by ZacSweers** [comment]
I'm not 100% sure but I think this reproduces it in a slightly different way: https://github.com/slackhq/slack-gradle-plugin/pull/934

If you clone that branch and run `./gradlew sortDependencies` it'll crash just before the trace above does

```
> Task :agp-handlers:agp-handler-api:sortDependencies FAILED
Exception in thread "main" java.lang.NullPointerException
        at cash.grammar.kotlindsl.utils.DependencyExtractor.parseDependencyDeclaration(DependencyExtractor.kt:189)
        at cash.grammar.kotlindsl.utils.DependencyExtractor.collectDependencies(DependencyExtractor.kt:48)
        at com.squareup.sort.kotlin.KotlinSorter.enterNamedBlock(KotlinSorter.kt:84)
        at com.squareup.cash.grammar.KotlinParser$NamedBlockContext.enterRule(KotlinParser.java:1491)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at cash.grammar.kotlindsl.parse.Parser.listener(Parser.kt:96)
        at com.squareup.sort.kotlin.KotlinSorter$Companion.of(KotlinSorter.kt:182)
        at com.squareup.sort.Sorter$Companion.of(Sorter.kt:20)
        at com.squareup.sort.SortCommand$sort$1.invoke(SortCommand.kt:118)
        at com.squareup.sort.SortCommand$sort$1.invoke(SortCommand.kt:116)
        at com.squareup.sort.SortCommand.sort$lambda$0(SortCommand.kt:116)

```

**Comment by ZacSweers** [comment]
after testing, it looks like the problem is the `gradleApi()` usages

**Comment by autonomousapps** [comment]
Will release as 0.9 (at some point).
