### ISSUE TITLE
IllegalArgumentException: List has more than one element when BOM is included

### ISSUE THREAD

**Issue by lydavid** [square/gradle-dependencies-sorter#112]
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: List has more than one element.

	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:610)
	at cash.grammar.kotlindsl.utils.DependencyExtractor.findIdentifier(DependencyExtractor.kt:221)
	at cash.grammar.kotlindsl.utils.DependencyExtractor.parseDependencyDeclaration(DependencyExtractor.kt:139)
	at cash.grammar.kotlindsl.utils.DependencyExtractor.collectDependencies(DependencyExtractor.kt:48)
```

When I remove the BOM, this goes away.

Example build.gradle.kts that failed until I commented out the BOM:
```kotlin
plugins {
    id("ly.david.musicsearch.kotlin.multiplatform")
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(projects.shared.domain)
                implementation(projects.core.logging.api)
                implementation(libs.koin.core)
//                implementation(project.dependencies.platform(libs.ktor.bom))
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.serialization.kotlinx.json)
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(libs.kotlin.test)
            }
        }
    }
}
```

There's some GHA runs seen here: https://github.com/lydavid/MusicSearch/pull/1069

**Comment by dees91** [comment]
kind of workaround - create ext function:
```kotlin
fun KotlinDependencyHandler.platformBillsOfMaterials(dependencyProvider: Provider<MinimalExternalModuleDependency>) {
    implementation(project.dependencies.platform(dependencyProvider))
}
```
and then declare dependency as:
```kotlin
platformBillsOfMaterials(libs.kotlin.faker.bom)
```

not ideal, but until resolved on the `gradle-dependencies-sorter` side, sorting works and bom works

**Comment by bmesing** [comment]
Hi, any timetable on this one? For our KMP project this is affecting quite a lot of modules.
