### ISSUE TITLE
fixDependencies: support for calling add function

### ISSUE THREAD

**Issue by kozaxinan** [square/gradle-dependencies-sorter#57]
Our project have different variants and we use `add` function to add variant specific dependencies. 
```
add("<variantName>Implementation", projects.foo)
add("debugImplementation", projects.foo)
```

This throw parsing exception with following stacktrace.

```
Caused by: com.squareup.parse.BuildScriptParseException: 1: extraneous input ',' expecting {'}', ID}
	at app//com.squareup.parse.BuildScriptParseException$Companion.withErrors(BuildScriptParseException.kt:9)
	at app//com.squareup.sort.Sorter.rewritten(Sorter.kt:76)
	at com.squareup.sort.SorterSpec.keep identical dependencies that have non-identical comments(SorterSpec.groovy:422)
```

Our actual usecase uses arrays and forEach method for different variant groups.
```
arrayOf("variantA", "variantB").forEach {
  add("${it}Implementation", projects.foo)
}
```

**Comment by autonomousapps** [comment]
Thanks for the issue. `fixDependencies` is a best effort to help migrate "normal" build scripts. Providing support for arbitrary functionality like this is outside of the scope of what we can support.
